"""add author_id to book table

Revision ID: a11df42fc3a0
Revises: 14ef0cc5c109
Create Date: 2025-06-23 13:23:48.940296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a11df42fc3a0'
down_revision = '14ef0cc5c109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('book_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])
        batch_op.drop_column('b_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('book_ibfk_1'), 'author', ['b_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
